config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :campaigns
  get 'welcome/index'
    
    

authenticated :user do
  root :to => "campaigns#index"
end
    root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
    belongs_to :user
    mount_uploader :campaign_file, CampaignUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :campaigns
      

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index,:show]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
      @campaign = current_user.campaigns.build
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = current_user.campaigns.build(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:title, :start_date, :end_date, :theaters)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
    def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/campaigns/_form.html.erb
<%= form_for(campaign) do |f| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :campaign_file %>
    <%= f.file_field :campaign_file %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>

  <div class="field">
    <%= f.label :theaters %>
    <%= f.text_field :theaters %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse navbar-full">
    
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    
  <a class="navbar-brand" href="#">Localee</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    
        <li class="nav-item">
          <a class="nav-link" href="#HowItWorks">Campaigns</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#Advertisers">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#Advertisers">Reports</a>
        </li>       
    </ul>
      
     <ul class="nav navbar-nav pull-xs-right">
      <% if user_signed_in? %>
            <li class="nav-item pull-lg-right">
          <%= link_to('Log out', destroy_user_session_path, :method => :delete, :class => "nav-link") %>
      </li>
      <% else %>          
    
    <li class="nav-item pull-lg-right">
                <%= link_to "Log in", new_user_session_path, :class => "nav-link" %>
      </li>
        <% end %>

    </ul>  

  </div>
</nav>
  
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
        <h1>Welcome, User</h1>
    </div>

    <div class="col-sm-6 pull-sm-right">
        <%= link_to 'New Campaign', new_campaign_path, :class=>  "btn btn-primary btn-sm" %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                <button class="dropdown-item" type="button">Action</button>
                <button class="dropdown-item" type="button">Another action</button>
                <button class="dropdown-item" type="button">Something else here</button>
              </div>
            </div>
    </div>
  </div>
</div>




<table>
  <thead>
    <tr>      
      <th>Title</th>
        <th>File</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Theaters</th>
      <th>User Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>        
        <td><%= campaign.title %></td>
          <tr>    
        <td><%= campaign.campaign_file %></td>
              <tr>    
        <td><%= campaign.start_date %></td>
        <td><%= campaign.end_date %></td>
        <td><%= campaign.theaters %></td>
        <td><%= campaign.user.email %></td>
        <td><%= link_to 'Show', campaign %></td>
          <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
        <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @campaign.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @campaign.campaign_file %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @campaign.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @campaign.end_date %>
</p>

<p>
  <strong>Theaters:</strong>
  <%= @campaign.theaters %>
</p>

<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Localee</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


    
  <body>   
   
    <div class="container-fluid">         
      
      <%= yield %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <title>The name of your site</title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %> 
    <%= stylesheet_link_tag "welcome.scss" %>
</head>


<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse navbar-full">
    
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    
  <a class="navbar-brand" href="#">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
          <a class="nav-link" href="#HowItWorks">How it works</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#Advertisers">Advertisers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#Advertisers">Agencies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#Theaters">Theaters</a>
        </li>
    </ul>
      
     <ul class="nav navbar-nav pull-xs-right">
      <% if user_signed_in? %>
            <li class="nav-item pull-lg-right">
          <%= link_to('Log out', destroy_user_session_path, :method => :delete, :class => "nav-link") %>
      </li>
      <% else %>          
    
      <li class="nav-item">
          <%= link_to "Sign Up Free", new_user_registration_path, :class => "btn btn-outline-success btn-sm" %>
      </li>
            <li class="nav-item pull-lg-right">
                <%= link_to "Log in", new_user_session_path, :class => "nav-link" %>
      </li>
        <% end %>

    </ul>  

  </div>
</nav>
    

<body> 
    
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <%= link_to image_tag('working.jpg') %> 
            <div class="carousel-caption">
            <h3>We are changing advertising on Main street.</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo accusamus voluptates aperiam tempore velit, est deleniti sequi, quisquam ad ratione odit omnis, at officiis quod molestias obcaecati eos perferendis. Esse.</p>
            </div>
        </div>        
        <div class="carousel-item">
          <%= link_to image_tag('spiderweb.jpg') %> 
        </div>
        <div class="carousel-item">
          <%= link_to image_tag('guitar.jpg') %> 
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
</div>
  

    
    
<div class="row">
   <section id="HowItWorks" class="feature-dark">
        <div class="row">
            <div class="col-sm-6"></div>
            <div class="col-sm-4">
                <h1>How it works</h1>
                <h2>Change your ad at any time </h2>
                <h3>Choose the theaters that apply to your market </h3>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente totam non tempora, a! Error magni id vero iusto natus officiis mollitia, similique aliquid dolore deleniti sed repellat vitae, saepe illum.</p>
                <a href="#home" role="button" class="btn btn-success-outlin byn-lg">Learn More</a>
            </div>
        </div>  
    </section>
</div>
</body>
</html>